### PR TITLE
Cross build scala 2.12 with Spark 3

### PR DESCRIPTION
**Pull request by zoltan-nagy**

### CODE REVIEW

**Review by BenFradet — COMMENTED** [review]
I think we can drop 2.11 support and move to 3.0.1 completely :+1:

**Comment by zoltan-nagy** [comment]
> I think we can drop 2.11 support and move to 3.0.1 completely 👍

Alright, I'll update the versions in this PR.

**Review by BenFradet — APPROVED** [review]
:+1:

**Comment by kmate** [comment]
@zoltan-nagy Travis might need changes as it has an image with Scala 2.11, right?

**Comment by zoltan-nagy** [comment]
Hey @BenFradet, thanks for reacting super fast on this change request. May I kindly ask you to release a new version of the lib?

Thanks,
Zoli

**Comment by BenFradet** [comment]
yes, I'll do that tomorrow :+1:

**Comment by zoltan-nagy** [comment]
Thank’s a lot!

**Comment by BenFradet** [comment]
should be on its way to central :+1:

**Comment by zoltan-nagy** [comment]
Thank you!

Ben Fradet <notifications@github.com> ezt írta (időpont: 2021. febr. 5., P
18:21):

**Pull request merged**
